### ISSUE TITLE
Error when downloading SA Client

### ISSUE THREAD

**Issue by alfredogangemi** [HCL-TECH-SOFTWARE/appscan-gitlab-integration#1]
Hi, 

Apparently the SA Client download link is invalid.

https://eu.cloud.appscan.com/api/SCX/StaticAnalyzer/SAClientUtil?os=linux
 
Can you point me to the right link? 
Thank you

**Comment by mattmurp** [comment]
Hi,

Thanks for pointing this out. The correct link is: https://eu.cloud.appscan.com/api/v4/Tools/SAClientUtil?os=linux

We'll get that corrected.

**Comment by alfredogangemi** [comment]
Thanks!
