### ISSUE TITLE
Fix: Handle separated SAST and SCA reports

### ISSUE THREAD

**Issue by alfredogangemi** [HCL-TECH-SOFTWARE/appscan-gitlab-integration#4]
Hi,

I noticed that in the latest SA Client update, the SAST and SCA scans have been separated, resulting in two distinct reports for each scan type. When running the `queue_analysis` command, the output now looks like this:

```bash
$ appscan.sh queue_analysis -a $appID >> output.txt
$ cat output.txt
100% transferred
SCA scan ID:  2ec88149-6bdd-467c-ba14-269fcd8ca461
SAST scan ID:  c143f2e0-1daa-40cc-80dc-9d8d57c69311
```
For this reason, the report check and issue calculation are no longer valid.  I have already submitted a [pull request](https://github.com/HCL-TECH-SOFTWARE/appscan-gitlab-integration/pull/3) that updates the code to save both reports as artifacts. Additionally, the issue calculation is now performed using the sum of both reports, ensuring the final result remains consistent with the previous behavior.

**Comment by mattmurp** [comment]
Thanks for creating this issue and the accompanying pull request. The reason the pull request has not been accepted, yet, is that we need to handle the case where a user only submits a SAST scan or only submits an SCA scan. This can happen under a few scenarios:

1. The user specifies the -oso option to the "appscan prepare" command, which indicates that only an SCA scan should be performed.
2. The user specifies the -sao option to the "appscan prepare" command, which indicates that only a SAST scan should be performed.
3. The user only has entitlement to SAST or SCA (not both), in which case a scan will only be created for the technology to which the user has entitlement.
